# Deployment file for Dounebain Diagnostics
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
  PROD_SERVER_SSH_PRIVATE_KEY: ${{ secrets.DDL_HMIS_SERVER_PRIVATE_KEY }}
  PROD_SERVER_IP: ${{ secrets.DDL_HMIS_SERVER_IP }}
  PROD_SERVER_USERNAME: ${{ secrets.DDL_HMIS_SERVER_USER }}

jobs:
  cleanup:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Docker system prune
        run: docker system prune -af
